import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Logic Link — Number Match Puzzle" },
      {
        name: "description",
        content:
          "A fair, deterministic number-matching puzzle. Every board is solvable, Add Row helps you smartly, and difficulty follows a sawtooth curve across 11 levels.",
      },
      { property: "og:title", content: "Logic Link — Number Match Puzzle" },
      {
        property: "og:description",
        content:
          "Every board is solvable. Fair by design. Play the deterministic Number Match puzzle.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: LandingPage,
});

/** Decorative mini-board for the hero (a real solvable line: pairs + sum-10s). */
const HERO_ROW: Array<{ v: number; hot?: boolean }> = [
  { v: 3 },
  { v: 7, hot: true },
  { v: 5 },
  { v: 5 },
  { v: 2 },
  { v: 8, hot: true },
  { v: 9 },
  { v: 1 },
  { v: 4 },
];

function Feature({ title, body }: { title: string; body: string }) {
  return (
    <div className="rounded-2xl border border-border bg-card p-4">
      <div className="text-sm font-semibold text-foreground">{title}</div>
      <div className="mt-1 text-sm leading-relaxed text-muted-foreground">{body}</div>
    </div>
  );
}

function LandingPage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-3xl flex-col justify-center gap-8 px-6 py-16">
      <div className="flex flex-col gap-4">
        <span className="text-[11px] font-semibold uppercase tracking-[0.25em] text-primary">
          Number Match
        </span>
        <h1 className="text-5xl font-bold tracking-tight text-foreground">Logic Link</h1>
        <p className="max-w-xl text-base leading-relaxed text-muted-foreground">
          A deterministic take on the classic sum-to-10 puzzle. Match identical numbers or pairs
          that sum to 10 — across rows, columns, diagonals, and wrap-around. Every board is
          generated by a constraint solver, so it is always winnable, and difficulty rises and falls
          in a deliberate sawtooth across 11 levels.
        </p>
      </div>

      <div className="flex items-center gap-1.5" aria-hidden>
        {HERO_ROW.map((c, i) => (
          <span
            key={i}
            className={[
              "flex h-10 w-10 items-center justify-center rounded-lg border font-mono text-lg font-bold",
              c.hot
                ? "border-primary bg-primary text-primary-foreground shadow-[var(--shadow-elegant)]"
                : "border-border bg-card text-foreground shadow-[var(--shadow-cell)]",
            ].join(" ")}
          >
            {c.v}
          </span>
        ))}
      </div>

      <div>
        <Link
          to="/play"
          className="inline-flex items-center justify-center rounded-xl bg-[image:var(--gradient-primary)] px-7 py-3 text-base font-semibold text-primary-foreground shadow-[var(--shadow-elegant)] transition-all hover:brightness-110 active:scale-[0.98]"
        >
          Start playing
        </Link>
      </div>

      <div className="grid gap-3 sm:grid-cols-2">
        <Feature
          title="Always solvable"
          body="Every board starts as 3 rows of 27 numbers, validated by a solver before you ever see it."
        />
        <Feature
          title="Smart Add Row"
          body="Six per level. Each one analyzes the board and deals complements right below the numbers that need them."
        />
        <Feature
          title="Sawtooth difficulty"
          body="Levels 1–5 climb, 6 gives you a breather, 7–10 peak, and 11 lets you coast. No burnout."
        />
        <Feature
          title="Rescue guaranteed"
          body="Two unhelpful rows in a row? The next one always contains an instant match. Frustration capped."
        />
      </div>
    </main>
  );
}
