import type { LevelConfig } from "../types";

/**
 * Sawtooth difficulty curve (Levels 1-11).
 *
 * Rise: 1 → 5, relief at 6 (~ L3), rise: 7 → 10 (peak > L5), relief at 11.
 *
 * Every level starts with the same spec board: 3 full 9-column rows
 * (27 cells = 13 pairs + 1 singleton), so difficulty comes entirely from
 * composition, not board size:
 *   - `buriedPairWeight`: pairs split apart at layout time so they only
 *     match after the values between them clear,
 *   - `decoyWeight`: post-layout value scrambling,
 *   - `fairnessThreshold`: floor on the fraction of random playouts that
 *     clear an accepted board — lower floors admit boards that punish
 *     careless move ordering.
 *
 * The odd cell count means the initial board clears down to one leftover
 * cell, never to empty — winning always takes at least one Add Row press,
 * and since each press adds 9 cells (odd), wins land on odd press counts
 * (1, 3, 5). `expectedAddRowDistribution` (index = presses used) reflects
 * that; per spec, Level 1 wins with a single press ~90% of the time.
 *
 * `targetCompletionTime` follows the spec table (L1 45s, L3 90s, L5 150s,
 * L6 90s) with a smooth climb to L10; it is a probabilistic envelope for
 * player cohorts, not a timer. `completionProbability` is the mandatory
 * 95% completion bar, enforced by the simulation gate.
 *
 * Add-row budget stays at 6 for every level.
 */
export const LEVEL_CONFIGS: Record<number, LevelConfig> = {
  1: {
    id: 1,
    difficultyScore: 1,
    matchDensity: 0.7,
    directPairWeight: 0.9,
    buriedPairWeight: 0.08,
    clusteringWeight: 0.75,
    decoyWeight: 0.09,
    helperStrength: 0.95,
    cleanupPriority: 0.95,
    expectedAddRowDistribution: [0, 0.93, 0, 0.06, 0, 0.01, 0],
    targetCompletionTime: 45,
    completionProbability: 0.95,
    withinTargetProbability: 0.9,
    valvePressesLeft: 6,
    minMatchDensity: 0.7,
    minObviousDensity: 0.65,
    fairnessThreshold: 0.8,
    seedStrategy: "ruleBasedVaried",
    addRowBudget: 6,
    initialCellCount: 27,
    valueBias: 0.7,
    burialDepth: 1,
    addRowBuckets: { immediate: 0.7, deferred: 0.3, decoy: 0 },
  },
  2: {
    id: 2,
    difficultyScore: 2,
    matchDensity: 0.66,
    directPairWeight: 0.78,
    buriedPairWeight: 0.2,
    clusteringWeight: 0.65,
    decoyWeight: 0.07,
    helperStrength: 0.9,
    cleanupPriority: 0.9,
    expectedAddRowDistribution: [0, 0.87, 0, 0.11, 0, 0.02, 0],
    targetCompletionTime: 70,
    completionProbability: 0.95,
    withinTargetProbability: 0.95,
    valvePressesLeft: 5,
    minMatchDensity: 0.6,
    minObviousDensity: 0,
    fairnessThreshold: 0.6,
    seedStrategy: "ruleBasedVaried",
    addRowBudget: 6,
    initialCellCount: 27,
    valueBias: 0.5,
    burialDepth: 2,
    addRowBuckets: { immediate: 0.6, deferred: 0.35, decoy: 0.05 },
  },
  3: {
    id: 3,
    difficultyScore: 3,
    matchDensity: 0.62,
    directPairWeight: 0.68,
    buriedPairWeight: 0.3,
    clusteringWeight: 0.55,
    decoyWeight: 0.13,
    helperStrength: 0.84,
    cleanupPriority: 0.84,
    expectedAddRowDistribution: [0, 0.72, 0, 0.24, 0, 0.04, 0],
    targetCompletionTime: 90,
    completionProbability: 0.95,
    withinTargetProbability: 0.95,
    valvePressesLeft: 4,
    minMatchDensity: 0.5,
    minObviousDensity: 0,
    fairnessThreshold: 0.4,
    seedStrategy: "ruleBasedVaried",
    addRowBudget: 6,
    initialCellCount: 27,
    valueBias: 0.3,
    burialDepth: 2,
    addRowBuckets: { immediate: 0.5, deferred: 0.4, decoy: 0.1 },
  },
  4: {
    id: 4,
    difficultyScore: 4,
    matchDensity: 0.58,
    directPairWeight: 0.56,
    buriedPairWeight: 0.42,
    clusteringWeight: 0.48,
    decoyWeight: 0.16,
    helperStrength: 0.78,
    cleanupPriority: 0.78,
    expectedAddRowDistribution: [0, 0.71, 0, 0.24, 0, 0.05, 0],
    targetCompletionTime: 120,
    completionProbability: 0.95,
    withinTargetProbability: 0.95,
    valvePressesLeft: 3,
    minMatchDensity: 0.45,
    minObviousDensity: 0,
    fairnessThreshold: 0.3,
    seedStrategy: "ruleBasedVaried",
    addRowBudget: 6,
    initialCellCount: 27,
    valueBias: 0.3,
    burialDepth: 4,
    addRowBuckets: { immediate: 0.45, deferred: 0.45, decoy: 0.1 },
  },
  5: {
    id: 5,
    difficultyScore: 5,
    matchDensity: 0.54,
    directPairWeight: 0.45,
    buriedPairWeight: 0.55,
    clusteringWeight: 0.4,
    decoyWeight: 0.32,
    helperStrength: 0.72,
    cleanupPriority: 0.72,
    expectedAddRowDistribution: [0, 0.65, 0, 0.3, 0, 0.05, 0],
    targetCompletionTime: 150,
    completionProbability: 0.95,
    withinTargetProbability: 0.95,
    valvePressesLeft: 2,
    minMatchDensity: 0.38,
    minObviousDensity: 0,
    fairnessThreshold: 0.3,
    seedStrategy: "ruleBasedVaried",
    addRowBudget: 6,
    initialCellCount: 27,
    valueBias: 0.15,
    burialDepth: 6,
    addRowBuckets: { immediate: 0.4, deferred: 0.45, decoy: 0.15 },
  },
  // Relief level: eases back to ~L3 difficulty so the sawtooth dips before
  // the second climb; slightly more decoys than L3 so it still feels new.
  6: {
    id: 6,
    difficultyScore: 3,
    matchDensity: 0.62,
    directPairWeight: 0.66,
    buriedPairWeight: 0.32,
    clusteringWeight: 0.55,
    decoyWeight: 0.13,
    helperStrength: 0.84,
    cleanupPriority: 0.84,
    expectedAddRowDistribution: [0, 0.78, 0, 0.19, 0, 0.03, 0],
    targetCompletionTime: 90,
    completionProbability: 0.95,
    withinTargetProbability: 0.95,
    valvePressesLeft: 4,
    minMatchDensity: 0.5,
    minObviousDensity: 0,
    fairnessThreshold: 0.45,
    seedStrategy: "ruleBasedVaried",
    addRowBudget: 6,
    initialCellCount: 27,
    valueBias: 0.35,
    burialDepth: 2,
    addRowBuckets: { immediate: 0.5, deferred: 0.4, decoy: 0.1 },
  },
  7: {
    id: 7,
    difficultyScore: 5,
    matchDensity: 0.55,
    directPairWeight: 0.5,
    buriedPairWeight: 0.42,
    clusteringWeight: 0.42,
    decoyWeight: 0.19,
    helperStrength: 0.73,
    cleanupPriority: 0.73,
    expectedAddRowDistribution: [0, 0.7, 0, 0.26, 0, 0.04, 0],
    targetCompletionTime: 165,
    completionProbability: 0.95,
    withinTargetProbability: 0.95,
    valvePressesLeft: 3,
    minMatchDensity: 0.42,
    minObviousDensity: 0,
    fairnessThreshold: 0.4,
    seedStrategy: "ruleBasedVaried",
    addRowBudget: 6,
    initialCellCount: 27,
    valueBias: 0.15,
    burialDepth: 5,
    addRowBuckets: { immediate: 0.35, deferred: 0.45, decoy: 0.2 },
  },
  8: {
    id: 8,
    difficultyScore: 6,
    matchDensity: 0.53,
    directPairWeight: 0.42,
    buriedPairWeight: 0.6,
    clusteringWeight: 0.36,
    decoyWeight: 0.3,
    helperStrength: 0.68,
    cleanupPriority: 0.68,
    expectedAddRowDistribution: [0, 0.69, 0, 0.27, 0, 0.04, 0],
    targetCompletionTime: 180,
    completionProbability: 0.95,
    withinTargetProbability: 0.95,
    valvePressesLeft: 2,
    minMatchDensity: 0.34,
    minObviousDensity: 0,
    fairnessThreshold: 0.3,
    seedStrategy: "ruleBasedVaried",
    addRowBudget: 6,
    initialCellCount: 27,
    valueBias: 0.1,
    burialDepth: 7,
    addRowBuckets: { immediate: 0.3, deferred: 0.45, decoy: 0.25 },
  },
  9: {
    id: 9,
    difficultyScore: 7,
    matchDensity: 0.51,
    directPairWeight: 0.36,
    buriedPairWeight: 0.66,
    clusteringWeight: 0.3,
    decoyWeight: 0.38,
    helperStrength: 0.64,
    cleanupPriority: 0.64,
    expectedAddRowDistribution: [0, 0.62, 0, 0.3, 0, 0.08, 0],
    targetCompletionTime: 195,
    completionProbability: 0.95,
    withinTargetProbability: 0.95,
    valvePressesLeft: 2,
    minMatchDensity: 0.3,
    minObviousDensity: 0,
    fairnessThreshold: 0.25,
    seedStrategy: "ruleBasedVaried",
    addRowBudget: 6,
    initialCellCount: 27,
    valueBias: 0.05,
    burialDepth: 7,
    addRowBuckets: { immediate: 0.25, deferred: 0.45, decoy: 0.3 },
  },
  10: {
    id: 10,
    difficultyScore: 8,
    matchDensity: 0.5,
    directPairWeight: 0.3,
    buriedPairWeight: 0.68,
    clusteringWeight: 0.25,
    decoyWeight: 0.5,
    helperStrength: 0.64,
    cleanupPriority: 0.6,
    expectedAddRowDistribution: [0, 0.62, 0, 0.31, 0, 0.07, 0],
    targetCompletionTime: 210,
    completionProbability: 0.95,
    withinTargetProbability: 0.95,
    valvePressesLeft: 2,
    minMatchDensity: 0.25,
    minObviousDensity: 0,
    fairnessThreshold: 0.25,
    seedStrategy: "ruleBasedVaried",
    addRowBudget: 6,
    initialCellCount: 27,
    valueBias: 0.05,
    burialDepth: 8,
    addRowBuckets: { immediate: 0.2, deferred: 0.45, decoy: 0.35 },
  },
  // Second relief level, mirroring the L6 dip after the L10 peak.
  11: {
    id: 11,
    difficultyScore: 3,
    matchDensity: 0.61,
    directPairWeight: 0.64,
    buriedPairWeight: 0.34,
    clusteringWeight: 0.55,
    decoyWeight: 0.34,
    helperStrength: 0.84,
    cleanupPriority: 0.84,
    expectedAddRowDistribution: [0, 0.77, 0, 0.19, 0, 0.04, 0],
    targetCompletionTime: 100,
    completionProbability: 0.95,
    withinTargetProbability: 0.95,
    valvePressesLeft: 4,
    minMatchDensity: 0.48,
    minObviousDensity: 0,
    fairnessThreshold: 0.45,
    seedStrategy: "ruleBasedVaried",
    addRowBudget: 6,
    initialCellCount: 27,
    valueBias: 0.12,
    burialDepth: 8,
    addRowBuckets: { immediate: 0.5, deferred: 0.4, decoy: 0.1 },
  },
};

export const LEVEL_IDS = Object.keys(LEVEL_CONFIGS)
  .map(Number)
  .sort((a, b) => a - b);

export function getLevelConfig(level: number): LevelConfig {
  const cfg = LEVEL_CONFIGS[level];
  if (!cfg) throw new Error(`Unknown level: ${level}`);
  return cfg;
}
