// Board pool baker (Phase 3).
//
// Generates candidate boards per level from the seeded PRNG, then filters:
//   1. skips safety-fallback boards (out-of-band difficulty by construction),
//   2. keeps boards whose scoreBoard value lands inside the D(L) tolerance band,
//   3. requires a constructive solver witness: a clear-to-empty path exists
//      within the level's Add Row press budget (DFS + move ordering, using
//      the exact deterministic rows index.addRow would inject).
//
// Survivors are written to src/engine/config/boardPool.json and shipped with
// the app. No generation happens at runtime — what was tested is what ships.
//
// Usage:
//   node --experimental-strip-types ...  (via vitest or a build tool)
//   npm run bake:boards -- --pool-size 16 --max-seeds 4000

import { getLevelConfig, LEVEL_IDS } from "../src/engine/config/levels";
import { generateBoard } from "../src/engine/generator";
import { scoreBoard, difficultyBand } from "../src/engine/difficulty";
import { isWinnableWithinBudget } from "../src/engine/solver";
import { boardAfterPress } from "../src/engine/index";
import { mulberry32 } from "../src/engine/rng";
import type { Board, GameState } from "../src/engine/types";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

type Args = { poolSize: number; maxSeeds: number; levels: number[] };

function parseArgs(argv: string[]): Args {
  const out: Args = { poolSize: 16, maxSeeds: 4000, levels: LEVEL_IDS };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--pool-size") out.poolSize = Number(argv[++i]);
    else if (a === "--max-seeds") out.maxSeeds = Number(argv[++i]);
    else if (a === "--levels")
      out.levels = argv[++i]
        .split(",")
        .map(Number)
        .filter((n) => Number.isFinite(n));
  }
  return out;
}

function serializeBoard(board: { row: { value: number | null }[] }[]): number[][] {
  return board.map((row) => row.map((cell) => cell.value as number));
}

async function main() {
  const { poolSize, maxSeeds, levels } = parseArgs(process.argv.slice(2));
  const t0 = Date.now();
  const out: Record<number, unknown> = {};

  for (const level of levels) {
    const config = getLevelConfig(level);
    const [lo, hi] = difficultyBand(level);
    const boards: { seed: number; score: number; values: number[][] }[] = [];

    for (let attempt = 1; attempt <= maxSeeds && boards.length < poolSize; attempt++) {
      const seed = (level * 1000003 + attempt * 997) >>> 0 || 1;
      const gen = generateBoard(config, seed);
      if (gen.usedFallback) continue;

      const score = scoreBoard(gen.board);
      if (score < lo || score > hi) continue;

      const pressRow = (board: Board, _r: () => number, moveCount: number) =>
        boardAfterPress({ board, level, seed, moveCount } as unknown as GameState);
      const winnable = isWinnableWithinBudget(gen.board, mulberry32(seed), {
        presses: config.addRowBudget,
        maxNodes: 60_000,
        pressRow,
      });
      if (!winnable) continue;

      boards.push({ seed, score, values: serializeBoard(gen.board) });
    }

    if (boards.length < poolSize) {
      console.error(
        `LEVEL ${level}: only ${boards.length}/${poolSize} boards in band [${lo.toFixed(1)}, ${hi.toFixed(1)}] after ${maxSeeds} seeds`,
      );
    } else {
      const mean = boards.reduce((s, b) => s + b.score, 0) / boards.length;
      console.log(
        `LEVEL ${level}: ${boards.length} boards baked, mean score ${mean.toFixed(2)} (band [${lo.toFixed(1)}, ${hi.toFixed(1)}])`,
      );
    }
    out[level] = {
      targetDifficulty: lo,
      band: [lo, hi],
      boards,
    };
  }

  const payload = {
    version: 1,
    note: "Generated by scripts/bake-boards.ts. Do not edit by hand.",
    levels: out,
  };

  const here = dirname(fileURLToPath(import.meta.url));
  const dest = join(here, "..", "src", "engine", "config", "boardPool.json");
  mkdirSync(dirname(dest), { recursive: true });
  writeFileSync(dest, JSON.stringify(payload, null, 2) + "\n");
  console.log(`\nWrote ${dest} in ${((Date.now() - t0) / 1000).toFixed(1)}s`);
}

main();
